name: Build Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
    
concurrency:
  group: environment-win-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
    steps:
      - name: Setup Pragma
        uses: Silverlan/pragma/github_actions/setup@main
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Build Dependencies
        uses: Silverlan/pragma/github_actions/build@main
        id: build-deps
        with:
          # This will build the core dependencies, as well as cycles, but not Pragma
          build-args: "--with-essential-client-modules=0 --with-common-modules=0 --with-lua-debugger=0 --module pr_unirender:\"https://github.com/Silverlan/pr_cycles.git\" --build 1 --build-cycles"

      - name: Copy UniRender_cycles files
        shell: bash
        run: |
          mkdir -p "release/modules/unirender"
          cp -r "${{ steps.build-deps.outputs.install-dir }}/modules/unirender/cycles" "release/modules/unirender"
        
      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
